# Generated by Django 6.0.1 on 2026-01-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
