# Generated by Django 6.0.1 on 2026-01-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recharge_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
