# Generated by Antigravity

from django.db import migrations

def apply_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    sql = """
    DO $$ 
    DECLARE 
        tables text[] := ARRAY[
            'auth_group', 'auth_group_permissions', 'auth_permission', 
            'auth_user', 'auth_user_groups', 'auth_user_user_permissions',
            'contact_logs', 'core_contactlog', 'core_recharge', 'core_settings',
            'django_admin_log', 'django_content_type', 'django_migrations', 
            'django_session', 'recharges', 'settings', 'users'
        ];
        t text;
    BEGIN
        FOREACH t IN ARRAY tables LOOP
            -- 1. Enable RLS (idempotent)
            EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
            
            -- 2. Create Policy for postgres/service_role (if not exists)
            BEGIN
                EXECUTE format('CREATE POLICY "allow_all_app_%I" ON public.%I FOR ALL TO postgres, service_role USING (true) WITH CHECK (true)', t, t);
            EXCEPTION WHEN duplicate_object THEN 
                NULL; -- Policy already exists, ignore
            END;
        END LOOP;
    END $$;
    """
    schema_editor.execute(sql)

def reverse_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    reverse_sql = """
    DO $$ 
    DECLARE 
        tables text[] := ARRAY[
            'auth_group', 'auth_group_permissions', 'auth_permission', 
            'auth_user', 'auth_user_groups', 'auth_user_user_permissions',
            'contact_logs', 'core_contactlog', 'core_recharge', 'core_settings',
            'django_admin_log', 'django_content_type', 'django_migrations', 
            'django_session', 'recharges', 'settings', 'users'
        ];
        t text;
    BEGIN
        FOREACH t IN ARRAY tables LOOP
            -- Drop Policy
            EXECUTE format('DROP POLICY IF EXISTS "allow_all_app_%I" ON public.%I', t, t);
            -- Disable RLS
            EXECUTE format('ALTER TABLE public.%I DISABLE ROW LEVEL SECURITY', t);
        END LOOP;
    END $$;
    """
    schema_editor.execute(reverse_sql)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recharge_local'),
        ('auth', '0001_initial'),
        ('sessions', '0001_initial'),
        ('admin', '0001_initial'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_rls, reverse_rls),
    ]
