# Generated by Antigravity

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_secure_rls'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='recharge',
                    name='latitude',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='recharge',
                    name='longitude',
                    field=models.FloatField(blank=True, null=True),
                ),
            ]
        )
    ]
