# Generated by Django 6.0.1 on 2026-08-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_settings_preco_kwh_medio_and_zero_exempt_recharges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='tipo_recarga',
            field=models.CharField(choices=[('AC', 'AC'), ('DC', 'DC')], default='AC', max_length=10),
        ),
    ]
